name: butler-blocks CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14.x

    - name: Install dependencies
      run: npm ci

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}


  test:
    name: Test
    needs: setup
    runs-on: ubuntu-latest

    steps:
    - name: Running Tests
      run: npm test

  build:
    name: Build
    needs: setup
    runs-on: ubuntu-latest

    steps:
    - name: Creating Build
      run: npm build
